version: "3.8"

services:
  agent-api:
    build: ./agent-api
    ports:
      - "8001:8000"
    container_name: pokemon-agent-api
    environment:
      - mcp_server_url=${mcp_server_url}
      - api_key=${api_key}
      - redis_host=${redis_host}
      - redis_port=${redis_port}
      - redis_password=${redis_password}






















